import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Nav} from "../components/Nav/Nav";
import {Jumbotron} from "../components/Jumbotron/Jumbotron";
import DefaultLayout from "../layouts/Default";


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <DefaultLayout>
            <Jumbotron />
        </DefaultLayout>
      </main>
    </div>
  )
}
